mysql:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_DATABASE:
            todo
        MYSQL_USER: todo
        MYSQL_ALLOW_EMPTY_PASSWORD:
            -yes
        MYSQL_ROOT_PASSWORD: root 
go:
    image: golang
    ports:
        - "8081:8081"
    links:
        - mysql:mysql
    volumes:
        - .:/go/src/todo
    command: /go/src/todo/start.sh
angular:
    image: nginx
    ports:
        - "8080:80"
    volumes:
        - ./angular:/usr/share/nginx/html

