mysql:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_DATABASE:
            todo
        MYSQL_USER: todo
        MYSQL_ALLOW_EMPTY_PASSWORD:
            -yes
        MYSQL_ROOT_PASSWORD: root 
